### ISSUE TITLE
Support for Timers

### ISSUE THREAD

**Issue by kumare3** [boto/botoflow#7]
Is this already supported? I was not able to find it.
http://docs.aws.amazon.com/amazonswf/latest/developerguide/swf-dg-timers.html

**Comment by darjus** [comment]
Hey Kumar,

Timers are supported, but weren't documented. I've updated the docs: https://botoflow.readthedocs.io/en/latest/reference/workflow_time.html

Let me know if it makes sense or not.

**Comment by kumare3** [comment]
@darjus This is great. I will try it out and if any problem will raise an issue. Lets close this one 👍 
BTW, great to run into you again, I think we worked around the same time at Amazon.
